# El modelo de regresión lineal simple

En un \emph{modelo de regresión simple}, suponemos que tenemos una \emph{variable independiente} $X_{0}$ (también conocida como \emph{variable explicativa} o \emph{predictora}), y una \emph{variable dependiente} $Y_{0}$ (también conocida como \emph{variable de respuesta}). Suponemos además que estas variables satisfacen una relación de la forma:
$$
Y_{0} = f_{0}(X_{0}) + \epsilon_0 
$$
donde $f_{0}$ es una función desconocida que describe la relación entre ambas variables, y $\epsilon_{0}$ es una variable aleatoria que representa el \emph{error} o \emph{ruido} en la relación entre $X_{0}$ e $Y_{0}$. Uno de los objetivos del \emph{aprendizaje estadístico} (también conocido como \emph{aprendizaje automático} o \emph{machine learning}), es tratar de aproximar la función $f_{0}$ a partir de un conjunto de datos 
$$
((x_{1},y_{1}),(x_{2},y_{2}),\ldots,(x_{n},y_{n}))
$$
dado. De manera más precisa, consideremos vectores aleatorios 
$$
X = \begin{bmatrix}
X_{1} \\
X_{2} \\
\vdots \\
X_{n}
\end{bmatrix}, \quad 
Y = \begin{bmatrix}
Y_{1} \\
Y_{2} \\
\vdots \\
Y_{n}
\end{bmatrix}
$$

que representan los posibles valores de las observaciones independientes y dependientes, respectivamente, en una muestra dada. En este contexto, un \emph{método de aprendizaje} consiste de una función $\hat{F}$, que depende de los vectores aleatorios $X$ e $Y$, y que cuando se evalúa en los datos observados produce una función $\hat{f}$ que aproxima a la función desconocida $f_{0}$. 

\begin{note} 
En muchos modelos de aprendizaje estadístico es común tomar el vector $X=x$ como fijo, en cuyo caso la función $\hat{F}$ depende únicamente del vector aleatorio $Y$. 
\end{note}

Para hacer estas ideas un poco más concretas, consideremos el caso particular en el que la función desconocida $f_{0}$ es una función lineal, es decir, 
$$
f_{0}(X_{0}) = b_{0} + b_{1} X_{0} 
$$
y supondremos además que $\epsilon_{0} \sim \mathcal{N}(0, \sigma^{2})$ es una variable aleatoria con distribución normal de media 0 y varianza $\sigma^{2}$. Este contexto se conoce como el \emph{modelo de regresión lineal simple} y es uno de los modelos más utilizados en aprendizaje estadístico. Notemos que en este caso nuestro objetivo es encontrar una expresión que nos permita aproximar los parámetros desconocidos $b_{0}$ y $b_{1}$ en términos de los datos observados. Para ello consideraremos las expresiones que obtuvimos en la sección anterior para los coeficientes de la recta de mejor ajuste por mínimos cuadrados, pero utilizando ahora el vector aleatorio $Y$ en lugar del vector de observaciones $y$. En otras palabras, definiremos 
$$
\Phi = \begin{bmatrix} 
1 & x_{1} \\
1 & x_{2} \\
\vdots & \vdots \\
1 & x_{n}
\end{bmatrix}
$$
y considereremos las matrices $D^{2} = (\Phi^{T} \Phi)^{-1}$, $A = D^{2} \Phi^{T}$ y $H = \Phi A$. Entonces podemos definir el \emph{vector aleatorio de estimadores de mínimos cuadrados} como:
$$
\hat{B} = AY
$$
Notemos que, ha diferencia de la sección anterior, en este caso $\hat{B}$ no es un vector de valores fijos, sino que es un vector aleatorio que depende linealmente del vector aleatorio $Y$. Además, de las propiedades de la distribución normal multivariada, sabemos que 
$$
\hat{B} \sim \mathcal{N}(b, \sigma^{2} D^{2})
$$
donde 
$$
b = \begin{bmatrix}
b_{0} \\
b_{1}
\end{bmatrix}
$$
es el vector de parámetros desconocidos. Notemos que, en particular, el vector aleatorio $\hat{B}$ es un estimador insesgado del vector de parámetros $b$, es decir, $E[\hat{B}] = b$. Notemos además que si evaluamos el vector aleatorio $\hat{B}$ en los datos observados $Y = y$, obtenemos el vector de coeficientes $\hat{\beta}$ de la recta de mejor ajuste por mínimos cuadrados que obtuvimos en la sección anterior. Una vez hechas estas observaciones, nuestro siguiente objetivo será construir los intervalos de confianza para los parámetros $b_{0}$ y $b_{1}$.

## Estimación de parámetros por intervalos de confianza

Empecemos por definir las cantidades 
\begin{align*}
d_0^{2} = & D^{2}_{11} = \frac{1}{n} + \frac{\bar{x}^{2}}{S_{xx}} \\ 
d_1^{2} = & D^{2}_{22} = \frac{1}{S_{xx}} \\
\end{align*}
donde 
$$
S_{xx} = \sum_{i=1}^{n} (x_{i} - \bar{x})^{2}
$$
tal y como lo habíamos definido en la sección anterior. Entonces 
\begin{align*} 
\hat{B}_{0} & \sim \mathcal{N}\left(b_{0}, \sigma^{2} d_0^{2}\right) \\ 
\hat{B}_{1} & \sim \mathcal{N}\left(b_{1}, \sigma^{2} d_1^{2}\right) 
\end{align*}
Consideremos ahora la variable aleatoria 
$$
\hat{S}^{2} = \frac{1}{n-2} \sum_{i=1}^{n} (Y_{i} - \hat{Y}_{i})^{2} 
$$
donde 
$$
\hat{Y} = \begin{bmatrix} 
\hat{Y}_{1} \\
\hat{Y}_{2} \\
\vdots \\
\hat{Y}_{n}
\end{bmatrix} = H Y 
$$
es el \emph{vector aleatorio de predicciones por mínimos cuadrados}. Entonces tenemos que 
$$
\frac{(n-2) \hat{S}^{2}}{\sigma^{2}} \sim \chi^{2}_{n-2} 
$$
y, además, la variable aleatoria $\hat{S}^{2}$ es independiente de las variables aleatorias $\hat{B}_{0}$ y $\hat{B}_{1}$. Por lo tanto, podemos construir las nuevas variables aleatorias 
\begin{align*}
T_{0} & = \frac{\hat{B}_{0} - b_{0}}{\hat{S} d_{0}} \sim t_{n-2} \\ 
T_{1} & = \frac{\hat{B}_{1} - b_{1}}{\hat{S} d_{1}} \sim t_{n-2}
\end{align*}
donde $t_{n-2}$ denota la distribución $t$ de Student con $n-2$ grados de libertad. Con esta información, podemos construir ahora los intervalos de confianza para los parámetros $b_{0}$ y $b_{1}$, tal y como nos lo habíamos propuesto. Empecemos por fijar un nivel de significancia $\alpha$ y sea $t_{\alpha/2, n-2}$ el cuantil superior de orden $\alpha/2$ de la distribución $t$ de Student correspondiente. Entonces, si tomamos $\hat{s}$ como el valor de la variable aleatoria $\hat{S}$ evaluada en el vector de datos observados $Y = y$, tenemos que los intervalos de confianza buscados son 
$$
(\hat{\beta}_{0} - t_{\alpha/2, n-2} \hat{s} d_{0},  \hat{\beta}_{0} + t_{\alpha/2, n-2} \hat{s} d_{0})
$$
para $b_{0}$, y 
$$
(\hat{\beta}_{1} - t_{\alpha/2, n-2} \hat{s} d_{1},  \hat{\beta}_{1} + t_{\alpha/2, n-2} \hat{s} d_{1})
$$
para $b_{1}$.

## Bandas de confianza y de predicción

Una vez obtenidos los intervalos de confianza para los parámetros $b_{0}$ y $b_{1}$, nos gustaría obtener ahora los intervalos de confianza para los posibles valores de la variable dependiente $Y_{0}$ en un valor específico de la variable independiente $X_{0} = x_{0}$. Para esto empezaremos por considerar la matriz de diseño en el punto $x_{0}$:
$$ 
\Phi_{0} = \begin{bmatrix}
1 & x_{0}
\end{bmatrix}
$$
y definiremos el vector aleatorio
$$ 
\hat{Y}_{0} = \Phi_{0} \hat{B} = \hat{B}_{0} + \hat{B}_{1} x_{0} 
$$
Notemos que este vector aleatorio depende solamente de las variables $\hat{B}_{0}$ y $\hat{B}_{1}$ (las cuales, a su vez, dependen solamente de las variables $Y_{1}, Y_{2}, \ldots, Y_{n}$), y es independiente de la variable aleatoria $Y_{0}$. Usando nuevamente las propiedades de la distribución normal multivariada, podemos ver que 
$$
\hat{Y}_{0} \sim \mathcal{N}\left( \Phi_{0}b, \sigma^{2} d_{c}^{2} \right) 
$$
donde 
$$
d_{c}^{2} = \Phi_{0} D^{2} \Phi_{0}^{T} = \frac{1}{n} + \frac{(x_{0} - \bar{x})^{2}}{S_{xx}} 
$$
Finalmente, como $\hat{Y}_{0}$ es independiente de la variable aleatoria $\hat{S}^{2}$, podemos construir la variable aleatoria 
$$
T_{c} = \frac{\hat{Y}_{0} - \Phi_{0} b}{\hat{S} d_{c}} \sim t_{n-2} 
$$
Se sigue que para construir un intervalo de confianza para el valor esperado de la variable dependiente $Y_{0}$ en el punto $X_{0} = x_{0}$, basta con tomar el intervalo 
$$
(\hat{y}_{0} - t_{\alpha/2, n-2} \hat{s} d_{c},  \hat{y}_{0} + t_{\alpha/2, n-2} \hat{s} d_{c})
$$
donde $\hat{y}_{0}$ es el valor de la variable aleatoria $\hat{Y}_{0}$ evaluada en los datos observados $Y = y$. Notemos que este intervalo depende del punto $X_{0} = x_{0}$ que hayamos elegido. De manera más general, podemos considerar el conjunto de todos los intervalos de confianza para todos los posibles valores de $x_{0}$, el cual se conoce como la \emph{banda de confianza} del modelo de regresión lineal simple.

Para terminar, notemos que como $Y_{0}$ es independiente de $\hat{Y}_{0}$, tenemos que 
$$
Y_{0} - \hat{Y}_{0} \sim \mathcal{N}(0, \sigma^{2} d_{p}^{2})
$$ 
donde
$$
d_{p}^{2} = 1 + d_{c}^{2} = 1 + \frac{1}{n} + \frac{(x_{0} - \bar{x})^{2}}{S_{xx}}
$$
Usando nuevamente la variable aleatoria $\hat{S}^{2}$, podemos definir ahora
$$
T_{p} = \frac{Y_{0} - \hat{Y}_{0}}{\hat{S} d_{p}} \sim t_{n-2}
$$
y, de manera similar a como lo hicimos antes, podemos construir un \emph{intervalo de predicción} para el valor de la variable dependiente $Y_{0}$ en el punto $X_{0} = x_{0}$ como 
$$
(\hat{y}_{0} - t_{\alpha/2, n-2} \hat{s} d_{p},  \hat{y}_{0} + t_{\alpha/2, n-2} \hat{s} d_{p})
$$
Nuevamente, el conjunto de todos estos intervalos de predicción para todos los posibles valores de $x_{0}$ se conoce como la \emph{banda de predicción} del modelo de regresión lineal simple.



