# Adecuación del modelo

### Modelo de regresión lineal múltiple
Hasta el momento hemos considerado únicamente modelos con una sola variable independiente.

\bigpause 

Sin embargo, en muchos casos es posible que la variable de interés dependa de múltiples variables independientes.

\bigpause

En este caso, el modelo de regresión lineal simple se extiende al modelo de regresión lineal múltiple, en el cual la variable dependiente $Y$ depende linealmente de múltiples variables independientes $X_{01}, X_{02}, \ldots, X_{0p}$. 

###

De manera más específica, supondremos que tenemos un modelo de la forma 
$$
Y_{0} = b_{0} + b_{1} X_{01} + b_{2} X_{02} + \cdots + b_{p} X_{0p} + \epsilon 
$$
\pause 

En este modelo, $Y_{0}$ es la variable dependiente 

\bigpause 

Las variables independientes son: $X_{01}, X_{02}, \ldots, X_{0p}$ 

\bigpause 

Los parámetros del modelo son: $b_{0}, b_{1}, \ldots, b_{p}$

\bigpause

El término de error está dado por 
$$
\epsilon \sim \mathcal{N}(0, \sigma^{2})
$$ 

###

Para considerar nuestras muestras de datos, consideraremos la matriz aleatoria 
$$
X = \begin{bmatrix}
X_{11} & X_{12} & \ldots & X_{1p} \\
X_{21} & X_{22} & \ldots & X_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
X_{n1} & X_{n2} & \ldots & X_{np}
\end{bmatrix}
$$
\pause

mantendremos el vector aleatorio 
$$
Y = \begin{bmatrix}
Y_{1} \\
Y_{2} \\
\vdots \\
Y_{n}
\end{bmatrix}
$$
que hemos utilizado anteriormente.

###

Supongamos ahora que tenemos un vector de observaciones independientes
$$
x = \begin{bmatrix} 
x_{11} & x_{12} & \ldots & x_{1p} \\
x_{21} & x_{22} & \ldots & x_{2p} \\
\vdots & \vdots & \ddots & \vdots \\
x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix}
$$
\pause

Entonces, podemos definir la matriz de diseño 
$$
\Phi = \begin{bmatrix}
1 & x_{11} & x_{12} & \ldots & x_{1p} \\ 
1 & x_{21} & x_{22} & \ldots & x_{2p} \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_{n1} & x_{n2} & \ldots & x_{np}
\end{bmatrix}
$$
y podemos definir las matrices $D^{2} = (\Phi^{T} \Phi)^{-1}$, $A = D^{2} \Phi^{T}$ y $H = \Phi A$.


### 

Entonces, el vector de coeficientes de la recta de mejor ajuste por mínimos cuadrados está dado por 
$$
\hat{B} = AY \sim \mathcal{N}(b, \sigma^{2} D^{2}) 
$$
mientras que el vector de predicciones está dado por 
$$
\hat{Y} = HY 
$$
Notemos que en este caso el estimador para la varianza del error está dado por 
$$
\hat{S}^{2} =\frac{ \|Y - \hat{Y}\|^{2}}{n - (p + 1)} = \sum_{i=1}^{n} \frac{(Y_{i} - \hat{Y}_{i})^{2}}{n - (p + 1)}
$$

### 

Ahora dado cualquier vector de observaciones dependientes 
$$
y = \begin{bmatrix}
y_{1} \\
y_{2} \\
\vdots \\
y_{n}
\end{bmatrix}
$$
podemos evaluar los estimadores anteriores en los datos observados para obtener el vector de coeficientes de la recta de mejor ajuste por mínimos cuadrados.

###

En particular, el vector de coeficientes está dado por 
$$
\hat{\beta} = \begin{bmatrix}
\hat{\beta}_{0} \\
\hat{\beta}_{1} \\
\vdots \\
\hat{\beta}_{p} 
\end{bmatrix} = A y
$$
\pause 
mientras que el vector de predicciones está dado por 
$$
\hat{y} = \begin{bmatrix} 
\hat{y}_{1} \\ 
\hat{y}_{2} \\ 
\vdots \\
\hat{y}_{n}
\end{bmatrix} = H y 
$$

###

Notemos que podemos realizar estos cálculos para cualquier conjunto de datos dados, sin embargo, para que el modelo de regresión lineal múltiple sea adecuado, es necesario que se cumplan ciertas condiciones. 


