# Introducción al Tidyverse

# Los momentos estandarizados

# Pruebas de normalidad

# Introducción al análisis multivariante

# Distribución normal multivariante

# Análisis de componentes principales

# Análisis factorial: modelos teóricos

### Análisis factorial: modelos teóricos 


El \alert{análisis factorial} es una técnica estadística ampliamente utilizada para identificar patrones ocultos o estructuras latentes detrás de grandes conjuntos de variables observadas.

\bigpause 

El objetivo es reducir la complejidad agrupando variables relacionadas en un número menor de \alert{factores} subyacentes, más fáciles de interpretar.

###

Algunas áreas de aplicación comunes incluyen:
\begin{itemize}
    \item \alert{Psicología y ciencias sociales:} rasgos latentes como inteligencia, ansiedad, dimensiones de personalidad o satisfacción. \pause
    \item \alert{Mercadotecnia e investigación de consumidores:} motivos de compra, percepciones de marca o segmentos. \pause
    \item \alert{Finanzas y economía:} factores ocultos de rendimientos, indicadores macro o riesgos. \pause
    \item \alert{Educación:} análisis de reactivos para medir habilidades comunes. \pause
    \item \alert{Ciencias biológicas y de la salud:} estructuras latentes en datos genéticos o reportes de pacientes. 
\end{itemize}

###

En la práctica, se usa cuando se sospecha que unas cuantas dimensiones no observadas explican las correlaciones entre muchas variables.

\bigpause

It is especially useful for building measurement scales, data reduction, and gaining insights into the structure of complex datasets.


## Factor Analysis Setting

### Factor Analysis Setting

The theoretical context for factor analysis is a relation of the form 
$$
X = \mu + LF + \epsilon 
$$
where:
\begin{itemize}
    \item $X$ is a random vector of $p$ observed variables (indicators). \pause
    \item $\mu$ is a constant vector of dimension $p$. \pause
    \item $L$ is a $p \times m$ constant matrix known as the matrix of \alert{factor loadings.} \pause
    \item $F \sim \N(0,I_{m})$ is a vector of $m$ latent factors (unobserved variables). \pause
    \item $\epsilon \sim \N(0,\Psi)$ is a vector of unique errors (specific variances), with $\Psi$ diagonal. \pause
    \item $F$ and $\epsilon$ are assumed to be independent, in particular $\Cov[F,\epsilon] = 0$.
\end{itemize}

###

As a consequence of these assumptions, we have that 
$$
\E[X] = \E[\mu + LF + \epsilon] = \E[\mu] + L\E[F] + \E[\epsilon] = \mu 
$$
\pause
and 
\begin{align*}
\Var[X] & = \Var[LF + \epsilon] \\
 & = \E[(LF + \epsilon)(LF + \epsilon)^{T}] \\
 & = \E[LF F^{T}L^{T}] + \E[\epsilon \epsilon^{T}] + \E[LF \epsilon^{T}] + \E[\epsilon F^{T}L^{T}] \\
  & = L \E[FF^{T}] L^{T} + \E[\epsilon \epsilon^{T}] + L \E[F \epsilon^{T}] + \E[\epsilon F^{T}] L^{T} \\
  & = L I_{m} L^{T} + \Psi + L 0 + 0 L^{T} \\
  & = LL^{T} + \Psi 
\end{align*}

\pause

Furthermore, since $X$ is a linear combination of normally distributed variables, it follows that 
$$
X \sim \N(\mu, LL^{T} + \Psi)
$$

## Variance Decomposition 

###

The variance decomposition $\Var[X] = LL^{T} + \Psi$ shows that the total variance of the observed variables $X$ can be decomposed into two components: \pause
\begin{itemize}
    \item \alert{Common variance ($LL^{T}$):} This part of the variance is explained by the common factors $F$. It captures the shared variability among the observed variables that can be attributed to the underlying latent structure. \pause
    \item \alert{Unique variance ($\Psi$):} This part of the variance is specific to each observed variable and is not explained by the common factors. It includes measurement errors and any other variability that is unique to each variable. 
\end{itemize}

\bigpause 

In particular, the variance of each individual observed variable $X_{i}$ can be expressed as 
$$ 
\Var[X_{i}] = \sum_{j=1}^{m} L_{ij}^{2} + \sigma_{i}^{2} 
$$
where $h_{i}^{2} = \sum_{j=1}^{m} L_{ij}^{2}$ is called the \alert{communality} of the variable $X_{i}$, representing the portion of its variance explained by the common factors, and $\sigma_{i}^{2}$ is the unique variance specific to $X_{i}$.

## Factor Score Estimation 

### Factor Score Estimation

Assume that we have a model 
$$
X = \mu + LF + \epsilon 
$$
with the same conditions as before.

\bigpause

Then the joint distribution of $X$ and $F$ is given by 
$$ 
\begin{bmatrix} 
X \\ F 
\end{bmatrix} \sim \N \left( 
\begin{bmatrix} 
\mu \\ 0 
\end{bmatrix},
\begin{bmatrix} 
LL^{T} + \Psi & L \\ 
L^{T} & I_{m} 
\end{bmatrix} 
\right) 
$$

\pause

Notice that, in particular,
$$
\Cov[X,F] = \E[(X - \mu)(F - 0)^{T}] = \E[(LF + \epsilon)F^{T}] = L \E[FF^{T}] + \E[\epsilon F^{T}] = L I_{m} + 0 = L 
$$

###

Using the properties of the multivariate normal distribution, we can derive the conditional distribution of the factors $F$ given the observed variables $X$.

\bigpause

This conditional distribution is also normal, with mean and covariance given by 
$$ 
[F | X = x] \sim \N \left( L^{T}(LL^{T} + \Psi)^{-1}(x - \mu), I_{m} - L^{T}(LL^{T} + \Psi)^{-1}L \right) 
$$ 

###

The mean of this conditional distribution, 
$$ 
\E[F | X = x] = L^{T}(LL^{T} + \Psi)^{-1}(x - \mu) 
$$ 
is known as the \alert{factor score} for the observed data point $X = x$.

\bigpause 

It provides an estimate of the latent factors based on the observed variables and the factor loadings.

\bigpause

The covariance matrix 
$$
I_{m} - L^{T}(LL^{T} + \Psi)^{-1}L 
$$ 
represents the uncertainty associated with the factor score estimates. 


###

\begin{remark} 
Notice that, if 
$$
f = \E[F | X = x] = L^{T}(LL^{T} + \Psi)^{-1}(x - \mu)
$$
then, in general, the \alert{residual}
$$ 
r(x) = x - \mu - Lf 
$$ 
is different from zero.

\bigpause

In fact, as a function of the random variable $X$, the residual has probability distribution 
$$
r(X) \sim \N\Big(0, L \left(I_m + L^T \Psi^{-1} L \right)^{-1} L^T + \Psi \Big)
$$

\end{remark}

## Rotation of Factors 

### Rotation of Factors

An important aspect of factor analysis is that the factors are not uniquely defined.

\bigpause

If $F$ is a vector of factors, then any orthogonal transformation $F^{*} = QF$, where $Q$ is an orthogonal matrix (i.e., $Q^{T}Q = I$), will yield a new set of factors that explain the same variance in the observed variables.

\bigpause

In particular, 
$$
\Var[F^{*}] = \Var[QF] = Q \Var[F] Q^{T} = Q I_{m} Q^{T} = I_{m} 
$$ 

\pause

The corresponding factor loadings will be transformed as 
$$
L^{*} = LQ^{T}
$$

###

In other words, if 
$$
X = \mu + LF + \epsilon
$$
is a valid factor model, then so is 
$$ 
X = \mu + L^{*}F^{*} + \epsilon = \mu + LQ^{T}QF + \epsilon = \mu + LF + \epsilon
$$ 

\pause

This means that the solution to a factor analysis problem is not unique, and different rotations of the factors can lead to different interpretations.

\pause 

In the next presentation, we will explore various practical methods for factor analysis and rotation techniques geared towards achieving more interpretable factor solutions.
